"""
Standard GCON event type definitions.
"""


class EventType:
    # Node Events
    NODE_REGISTERED = "NODE_REGISTERED"
    NODE_DEREGISTERED = "NODE_DEREGISTERED"
    NODE_ONLINE = "NODE_ONLINE"
    NODE_OFFLINE = "NODE_OFFLINE"
    NODE_IDLE = "NODE_IDLE"
    NODE_BUSY = "NODE_BUSY"

    # Job Events
    JOB_SUBMITTED = "JOB_SUBMITTED"
    JOB_ASSIGNED = "JOB_ASSIGNED"
    JOB_STARTED = "JOB_STARTED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"

    # Artifact Events
    ARTIFACT_REGISTERED = "ARTIFACT_REGISTERED"

    # Receipt Events
    RECEIPT_GENERATED = "RECEIPT_GENERATED"

    # System Events
    CLUSTER_STARTED = "CLUSTER_STARTED"
    CLUSTER_STOPPED = "CLUSTER_STOPPED"