"""
Standard GCON event type definitions.
"""


class EventType:
    # Node Events
    NODE_REGISTERED = "NODE_REGISTERED"
    NODE_DEREGISTERED = "NODE_DEREGISTERED"
    NODE_ONLINE = "NODE_ONLINE"
    NODE_OFFLINE = "NODE_OFFLINE"
    NODE_IDLE = "NODE_IDLE"
    NODE_BUSY = "NODE_BUSY"

    # Job Events
    JOB_SUBMITTED = "JOB_SUBMITTED"
    JOB_ASSIGNED = "JOB_ASSIGNED"
    JOB_STARTED = "JOB_STARTED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    JOB_CANCELLED = "JOB_CANCELLED"

    # Scheduler Events
    SCHEDULER_PAUSED = "SCHEDULER_PAUSED"
    SCHEDULER_RESUMED = "SCHEDULER_RESUMED"
    QUEUE_CLEARED = "QUEUE_CLEARED"
    FAILED_JOBS_RETRIED = "FAILED_JOBS_RETRIED"
    EMERGENCY_STOP = "EMERGENCY_STOP"

    # Node lifecycle Events
    NODE_DRAINING = "NODE_DRAINING"
    NODE_RESTARTED = "NODE_RESTARTED"

    # Artifact Events
    ARTIFACT_REGISTERED = "ARTIFACT_REGISTERED"

    # Receipt Events
    RECEIPT_GENERATED = "RECEIPT_GENERATED"

    # System Events
    CLUSTER_STARTED = "CLUSTER_STARTED"
    CLUSTER_STOPPED = "CLUSTER_STOPPED"

    # Health / Trust Events
    HEALTH_DEGRADED = "HEALTH_DEGRADED"
    HEALTH_CRITICAL = "HEALTH_CRITICAL"
    HEALTH_RECOVERED = "HEALTH_RECOVERED"
    RECEIPT_VERIFICATION_FAILED = "RECEIPT_VERIFICATION_FAILED"
    RECEIPT_VERIFICATION_RECOVERED = "RECEIPT_VERIFICATION_RECOVERED"