# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gcon.transport.proto import gcon_transport_pb2 as gcon__transport__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gcon_transport_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentControlStub:
    """AgentControl is served by the Coordinator over mTLS/HTTP2. Agent
    daemons are the gRPC *clients* -- they dial out to the coordinator
    and keep the Control stream open for the lifetime of the process.
    This is deliberate: worker machines are frequently behind NAT/
    firewalls with no inbound connectivity, while the coordinator is
    the one stable, routable endpoint in the cluster. Job assignment
    therefore flows coordinator -> agent as messages *down* a stream
    the agent itself opened, rather than the coordinator dialing out
    to agents.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/gcon.transport.v1.AgentControl/Register',
                request_serializer=gcon__transport__pb2.RegisterRequest.SerializeToString,
                response_deserializer=gcon__transport__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Control = channel.stream_stream(
                '/gcon.transport.v1.AgentControl/Control',
                request_serializer=gcon__transport__pb2.AgentEnvelope.SerializeToString,
                response_deserializer=gcon__transport__pb2.CoordinatorEnvelope.FromString,
                _registered_method=True)
        self.StreamLogs = channel.stream_unary(
                '/gcon.transport.v1.AgentControl/StreamLogs',
                request_serializer=gcon__transport__pb2.LogChunk.SerializeToString,
                response_deserializer=gcon__transport__pb2.LogAck.FromString,
                _registered_method=True)
        self.UploadReceipt = channel.unary_unary(
                '/gcon.transport.v1.AgentControl/UploadReceipt',
                request_serializer=gcon__transport__pb2.ReceiptUpload.SerializeToString,
                response_deserializer=gcon__transport__pb2.ReceiptAck.FromString,
                _registered_method=True)


class AgentControlServicer:
    """AgentControl is served by the Coordinator over mTLS/HTTP2. Agent
    daemons are the gRPC *clients* -- they dial out to the coordinator
    and keep the Control stream open for the lifetime of the process.
    This is deliberate: worker machines are frequently behind NAT/
    firewalls with no inbound connectivity, while the coordinator is
    the one stable, routable endpoint in the cluster. Job assignment
    therefore flows coordinator -> agent as messages *down* a stream
    the agent itself opened, rather than the coordinator dialing out
    to agents.
    """

    def Register(self, request, context):
        """One-time registration handshake. The client certificate presented
        during the TLS handshake is the agent's authenticated identity;
        Register additionally exchanges a human-readable node_id and
        capability facts and returns a short-lived session_token that
        must be presented on the Control stream, so a stolen/duplicated
        client cert alone is not sufficient to impersonate a node that
        is already connected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request_iterator, context):
        """Long-lived, agent-initiated, bidirectional control channel.
        Agent -> Coordinator: HEARTBEAT, JOB_RESULT, SHUTDOWN_NOTICE.
        Coordinator -> Agent: JOB_ASSIGN, JOB_CANCEL, PING.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request_iterator, context):
        """Client-streaming log upload for a single job attempt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadReceipt(self, request, context):
        """Receipt upload. Unary because receipts are small, signed JSON
        documents, not bulk data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=gcon__transport__pb2.RegisterRequest.FromString,
                    response_serializer=gcon__transport__pb2.RegisterResponse.SerializeToString,
            ),
            'Control': grpc.stream_stream_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=gcon__transport__pb2.AgentEnvelope.FromString,
                    response_serializer=gcon__transport__pb2.CoordinatorEnvelope.SerializeToString,
            ),
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=gcon__transport__pb2.LogChunk.FromString,
                    response_serializer=gcon__transport__pb2.LogAck.SerializeToString,
            ),
            'UploadReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadReceipt,
                    request_deserializer=gcon__transport__pb2.ReceiptUpload.FromString,
                    response_serializer=gcon__transport__pb2.ReceiptAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gcon.transport.v1.AgentControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gcon.transport.v1.AgentControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentControl:
    """AgentControl is served by the Coordinator over mTLS/HTTP2. Agent
    daemons are the gRPC *clients* -- they dial out to the coordinator
    and keep the Control stream open for the lifetime of the process.
    This is deliberate: worker machines are frequently behind NAT/
    firewalls with no inbound connectivity, while the coordinator is
    the one stable, routable endpoint in the cluster. Job assignment
    therefore flows coordinator -> agent as messages *down* a stream
    the agent itself opened, rather than the coordinator dialing out
    to agents.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gcon.transport.v1.AgentControl/Register',
            gcon__transport__pb2.RegisterRequest.SerializeToString,
            gcon__transport__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gcon.transport.v1.AgentControl/Control',
            gcon__transport__pb2.AgentEnvelope.SerializeToString,
            gcon__transport__pb2.CoordinatorEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/gcon.transport.v1.AgentControl/StreamLogs',
            gcon__transport__pb2.LogChunk.SerializeToString,
            gcon__transport__pb2.LogAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gcon.transport.v1.AgentControl/UploadReceipt',
            gcon__transport__pb2.ReceiptUpload.SerializeToString,
            gcon__transport__pb2.ReceiptAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
